### PR TITLE
Update depends and fix hex color formatting

### PR DESCRIPTION
**Pull request by rtm516**
I also changed the example code to use `mc.hypixel.net` as its a well known server.

This fixes the below error
```
java.lang.IllegalArgumentException: No enum constant net.md_5.bungee.api.ChatColor.#E89F00
	at java.base/java.lang.Enum.valueOf(Enum.java:240)
	at net.md_5.bungee.api.ChatColor.valueOf(ChatColor.java:11)
	at net.md_5.bungee.chat.BaseComponentSerializer.deserialize(BaseComponentSerializer.java:23)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:24)
	at net.md_5.bungee.chat.TextComponentSerializer.deserialize(TextComponentSerializer.java:16)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.internal.bind.TreeTypeAdapter$GsonContextImpl.deserialize(TreeTypeAdapter.java:162)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:92)
	at net.md_5.bungee.chat.ComponentSerializer.deserialize(ComponentSerializer.java:21)
	at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.ArrayTypeAdapter.read(ArrayTypeAdapter.java:72)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at net.md_5.bungee.chat.ComponentSerializer.parse(ComponentSerializer.java:42)
	at br.com.azalim.mcserverping.MCPing.getPing(MCPing.java:165)
```

### CODE REVIEW

**Comment by lamergameryt** [comment]
Perhaps not the right pull repository to ask this, but since you're changing the example file included with the repo perhaps you could also update the README.md as neither `MinecraftPingOptions` nor `MinecraftPingReply` are valid classes present within the library.

**Comment by rtm516** [comment]
> are valid classes present within the library.

Done :)

**Review by lamergameryt — APPROVED** [review]
Great work, hope this gets merged with the repository soon.

**Comment by lucaazalim** [comment]
Sorry for the delay and thank you very much for the PR.

I just changed the example server back to **redesky.com** since it is my server. It is always up and running so it serves well to the purpose of an example server to ping. Hypixel is already too famous.

**Comment by rtm516** [comment]
> Sorry for the delay and thank you very much for the PR.
> 
> I just changed the example server back to **redesky.com** since it is my server. It is always up and running so it serves well to the purpose of an example server to ping. Hypixel is already too famous.

No problem. Thanks for the note about Hypixel, the only reason I chose them is that they are reachable from anywhere and big enough to not go down anytime soon.

**Pull request merged**
